// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: player.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 玩家属性变化
type PlayerAttribute int32

const (
	PlayerAttribute_AA_AttributeNone PlayerAttribute = 0
)

var PlayerAttribute_name = map[int32]string{
	0: "AA_AttributeNone",
}

var PlayerAttribute_value = map[string]int32{
	"AA_AttributeNone": 0,
}

func (x PlayerAttribute) String() string {
	return proto.EnumName(PlayerAttribute_name, int32(x))
}

func (PlayerAttribute) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

// 玩家基本信息
type Player struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Exp                  int64    `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	Uid                  int64    `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *Player) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Player) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Player) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// 查询角色响应
type PlayerSelectResponse struct {
	List                 []*Player `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerSelectResponse) Reset()         { *m = PlayerSelectResponse{} }
func (m *PlayerSelectResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerSelectResponse) ProtoMessage()    {}
func (*PlayerSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}
func (m *PlayerSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSelectResponse.Unmarshal(m, b)
}
func (m *PlayerSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSelectResponse.Marshal(b, m, deterministic)
}
func (m *PlayerSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSelectResponse.Merge(m, src)
}
func (m *PlayerSelectResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerSelectResponse.Size(m)
}
func (m *PlayerSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSelectResponse proto.InternalMessageInfo

func (m *PlayerSelectResponse) GetList() []*Player {
	if m != nil {
		return m.List
	}
	return nil
}

// 请求创建角色
type PlayerCreateRequest struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Gender               int32    `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateRequest) Reset()         { *m = PlayerCreateRequest{} }
func (m *PlayerCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateRequest) ProtoMessage()    {}
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}
func (m *PlayerCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateRequest.Unmarshal(m, b)
}
func (m *PlayerCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateRequest.Marshal(b, m, deterministic)
}
func (m *PlayerCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateRequest.Merge(m, src)
}
func (m *PlayerCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateRequest.Size(m)
}
func (m *PlayerCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateRequest proto.InternalMessageInfo

func (m *PlayerCreateRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerCreateRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

// 创建角色回应
type PlayerCreateResponse struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateResponse) Reset()         { *m = PlayerCreateResponse{} }
func (m *PlayerCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateResponse) ProtoMessage()    {}
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}
func (m *PlayerCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateResponse.Unmarshal(m, b)
}
func (m *PlayerCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateResponse.Marshal(b, m, deterministic)
}
func (m *PlayerCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateResponse.Merge(m, src)
}
func (m *PlayerCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateResponse.Size(m)
}
func (m *PlayerCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateResponse proto.InternalMessageInfo

func (m *PlayerCreateResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// 进入游戏响应
type PlayerEnterResponse struct {
	GuideMaps            map[int32]int32 `protobuf:"bytes,2,rep,name=guideMaps,proto3" json:"guideMaps,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlayerEnterResponse) Reset()         { *m = PlayerEnterResponse{} }
func (m *PlayerEnterResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerEnterResponse) ProtoMessage()    {}
func (*PlayerEnterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}
func (m *PlayerEnterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerEnterResponse.Unmarshal(m, b)
}
func (m *PlayerEnterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerEnterResponse.Marshal(b, m, deterministic)
}
func (m *PlayerEnterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerEnterResponse.Merge(m, src)
}
func (m *PlayerEnterResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerEnterResponse.Size(m)
}
func (m *PlayerEnterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerEnterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerEnterResponse proto.InternalMessageInfo

func (m *PlayerEnterResponse) GetGuideMaps() map[int32]int32 {
	if m != nil {
		return m.GuideMaps
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.PlayerAttribute", PlayerAttribute_name, PlayerAttribute_value)
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*PlayerSelectResponse)(nil), "pb.PlayerSelectResponse")
	proto.RegisterType((*PlayerCreateRequest)(nil), "pb.PlayerCreateRequest")
	proto.RegisterType((*PlayerCreateResponse)(nil), "pb.PlayerCreateResponse")
	proto.RegisterType((*PlayerEnterResponse)(nil), "pb.PlayerEnterResponse")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.PlayerEnterResponse.GuideMapsEntry")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0x93, 0x26, 0xda, 0x51, 0xb4, 0xac, 0x45, 0x96, 0x1e, 0x4a, 0xc8, 0x41, 0x83, 0x87,
	0x08, 0x0a, 0x22, 0xc5, 0x4b, 0xd5, 0x22, 0x1e, 0x5a, 0x64, 0xf5, 0xe4, 0x45, 0x92, 0x66, 0x28,
	0xc1, 0x34, 0x59, 0x93, 0x4d, 0xb1, 0x3f, 0xc5, 0x3f, 0xe2, 0xef, 0x93, 0xec, 0x26, 0xfd, 0xf0,
	0xe0, 0x6d, 0xde, 0x9b, 0x79, 0x33, 0xef, 0x25, 0x0b, 0x07, 0x22, 0x09, 0x96, 0x98, 0xfb, 0x22,
	0xcf, 0x64, 0x46, 0x0d, 0x11, 0xba, 0x3f, 0x04, 0xec, 0x67, 0x45, 0xd2, 0x1e, 0xec, 0xe9, 0xf6,
	0x53, 0xc4, 0x88, 0x43, 0x3c, 0x93, 0xaf, 0x30, 0xed, 0x03, 0xe8, 0x7a, 0x12, 0xcc, 0x91, 0x19,
	0x0e, 0xf1, 0xda, 0x7c, 0x83, 0xa1, 0x27, 0x60, 0xcf, 0x30, 0x8d, 0x30, 0x67, 0xa6, 0x43, 0x3c,
	0x8b, 0xd7, 0x88, 0x76, 0xc1, 0x4a, 0x70, 0x81, 0x09, 0x6b, 0x29, 0x5a, 0x83, 0x6a, 0xdb, 0x34,
	0xc7, 0x40, 0xe2, 0x6b, 0x3c, 0x47, 0x66, 0xa9, 0x5b, 0x1b, 0x0c, 0xed, 0x80, 0x89, 0x5f, 0x82,
	0xd9, 0xaa, 0x51, 0x95, 0x15, 0x53, 0xc6, 0x11, 0xdb, 0xd5, 0x4c, 0x19, 0x47, 0xee, 0x35, 0x74,
	0xb5, 0xef, 0x17, 0x4c, 0x70, 0x2a, 0x39, 0x16, 0x22, 0x4b, 0x0b, 0xa4, 0x7d, 0x68, 0x25, 0x71,
	0x21, 0x19, 0x71, 0x4c, 0x6f, 0xff, 0x12, 0x7c, 0x11, 0xfa, 0x7a, 0x8e, 0x2b, 0xde, 0x1d, 0xc3,
	0xb1, 0xc6, 0xf7, 0xea, 0x1e, 0xc7, 0xcf, 0x12, 0x0b, 0xf9, 0x27, 0x20, 0xf9, 0x27, 0xa0, 0xb1,
	0x19, 0xd0, 0x1d, 0x34, 0x36, 0x9a, 0x75, 0xb5, 0x0d, 0x17, 0x6c, 0xad, 0x56, 0xbb, 0xb6, 0x8d,
	0xd4, 0x1d, 0xf7, 0x9b, 0x34, 0x5e, 0x46, 0xa9, 0xc4, 0x7c, 0xa5, 0x7d, 0x80, 0xf6, 0xac, 0x8c,
	0x23, 0x1c, 0x07, 0xa2, 0x60, 0x86, 0xca, 0x71, 0xba, 0x96, 0x6f, 0xcd, 0xfa, 0x8f, 0xcd, 0xe0,
	0x28, 0x95, 0xf9, 0x92, 0xaf, 0x85, 0xbd, 0x5b, 0x38, 0xdc, 0x6e, 0x56, 0x1f, 0xf1, 0x03, 0x97,
	0xca, 0x90, 0xc5, 0xab, 0xb2, 0xfa, 0x3d, 0x8b, 0x20, 0x29, 0xb1, 0x0e, 0xa5, 0xc1, 0xc0, 0xb8,
	0x21, 0xe7, 0x67, 0x70, 0xa4, 0xcf, 0x0d, 0xa5, 0xcc, 0xe3, 0xb0, 0x94, 0x48, 0xbb, 0xd0, 0x19,
	0x0e, 0xdf, 0x57, 0x78, 0x92, 0xa5, 0xd8, 0xd9, 0xb9, 0xb3, 0xde, 0xcc, 0x0b, 0x11, 0x86, 0xb6,
	0x7a, 0x52, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x3b, 0x88, 0x70, 0x62, 0x02, 0x00,
	0x00,
}
